### ISSUE TITLE
[bug] 400 Response Deserialization Fails

### ISSUE THREAD

**Issue by YanDoroshenko** [CyberSource/cybersource-rest-client-java#14]
Error response deserialization fails:
```
{"submitTimeUtc":"2019-02-05T11:49:07Z","status":"INVALID_REQUEST","reason":"INVALID_DATA","message":"Declined - One or more fields in the request contains invalid data","details":[{"field":"recipientInformation.card.expirationMonth","reason":"INVALID_DATA"}]}

closed
java.lang.IllegalStateException: closed
	at com.squareup.okhttp.internal.http.Http1xStream$FixedLengthSource.read(Http1xStream.java:390)
	at okio.Buffer.writeAll(Buffer.java:956)
	at okio.RealBufferedSource.readByteArray(RealBufferedSource.java:92)
	at com.squareup.okhttp.ResponseBody.bytes(ResponseBody.java:57)
	at com.squareup.okhttp.ResponseBody.string(ResponseBody.java:83)
	at Invokers.ApiClient.handleResponse(ApiClient.java:1170)
	at Invokers.ApiClient.execute(ApiClient.java:1074)
	at Api.PaymentsApi.createPaymentWithHttpInfo(PaymentsApi.java:154)
```

Version: 0.0.7

**Comment by YanDoroshenko** [comment]
I used the sample data from the samples project except changing a month value to 13.

**Comment by gnongsie** [comment]
Hi,
We do have some issues with deserialization of error responses. Please be patient and we will resolve this at the earliest.

**Comment by gnongsie** [comment]
This has since been fixed. I am closing this issue. Kindly open a new issue if you still have some doubts.
