### ISSUE TITLE
Call generatePublicKey fails when upgrading jdk version to 16

### ISSUE THREAD

**Issue by ZakariaBenjebara** [CyberSource/cybersource-rest-client-java#99]
We encounter this issue with `generatePublicKey ` call when updating jdk version from 14 to 16.
```java
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected java.io.Reader() accessible: module java.base does not "opens java.io" to unnamed module @1b1473ab
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Constructor.checkCanSetAccessible(Constructor.java:188)
	at java.base/java.lang.reflect.Constructor.setAccessible(Constructor.java:181)
	at com.google.gson.internal.reflect.UnsafeReflectionAccessor.makeAccessible(UnsafeReflectionAccessor.java:44)
	at com.google.gson.internal.ConstructorConstructor.newDefaultConstructor(ConstructorConstructor.java:103)
	at com.google.gson.internal.ConstructorConstructor.get(ConstructorConstructor.java:85)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:101)
	at com.google.gson.Gson.getAdapter(Gson.java:458)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:117)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:166)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102)
	at com.google.gson.Gson.getAdapter(Gson.java:458)
	at com.google.gson.Gson.toJson(Gson.java:696)
	at com.google.gson.Gson.toJson(Gson.java:683)
	at com.google.gson.Gson.toJson(Gson.java:638)
	at com.google.gson.Gson.toJson(Gson.java:618)
	at Invokers.JSON.serialize(JSON.java:83)
	at Invokers.ApiClient.execute(ApiClient.java:1204)
	at Api.KeyGenerationApi.generatePublicKeyWithHttpInfo(KeyGenerationApi.java:168)
	at Api.KeyGenerationApi.generatePublicKey(KeyGenerationApi.java:152)
```

**Comment by gnongsie** [comment]
Hi @ZakariaBenjebara,

As mentioned in our [README.md](https://github.com/CyberSource/cybersource-rest-client-java#requirements) file,

> **Support for higher versions of JDK (>= 1.9.0) has not been made available.**
